# Generated by Django 5.2.1 on 2025-06-19 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0014_alter_pedido_estado_alter_pedido_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='pedido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='ferreteria.pedido'),
        ),
    ]
