# Generated by Django 5.2.1 on 2025-06-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0015_boleta_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='pedido',
        ),
    ]
